name: Add Notification

on:
  workflow_dispatch:
    inputs:
      Title:
        description: 'Notification Title'
        required: true
      Message:
        description: 'Notification Message'
        required: true
      Type:
        description: 'Notification Type'
        required: true
        default: 'Info'

jobs:
  AddNotification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Add Notification To File
        run: |
          FILE="Notifications.json"

          if [ ! -f "$FILE" ]; then
            echo "[]" > "$FILE"
          fi

          EXISTING=$(cat "$FILE")

          ID=$(uuidgen)
          
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%S.%3NZ")
          
          NEW=$(jq -n --arg Id "$ID" \
                       --arg Title "${{ github.event.inputs.Title }}" \
                       --arg Message "${{ github.event.inputs.Message }}" \
                       --arg Type "${{ github.event.inputs.Type }}" \
                       --arg Timestamp "$TIMESTAMP" \
                       '{Id:$Id, Title:$Title, Message:$Message, Type:$Type, Timestamp:$Timestamp, Read:false}')

          UPDATED=$(echo "$EXISTING" | jq --argjson new "$NEW" \
                       'if any(.[]; .Title == $new.Title and .Message == $new.Message and .Timestamp == $new.Timestamp) then . else . + [$new] end')

          UPDATED=$(echo "$UPDATED" | jq ".[-50:]")

          if [ "$(echo "$EXISTING" | jq -c '.')" != "$(echo "$UPDATED" | jq -c '.')" ]; then
            echo "$UPDATED" | jq '.' > "$FILE"
          fi

      - name: Commit And Push Changes
        run: |
          git config user.name "GitHub-Actions[Bot]"
          git config user.email "GitHub-Actions[Bot]@users.noreply.github.com"
          git add Notifications.json
          if ! git diff --cached --quiet; then
            git commit -m "Notification Added"
            git push
          fi
